### ISSUE TITLE
`gen` verification on v6.4+ takes weeks

### ISSUE THREAD

**Issue by pchaigno** [bpfverif/agni#13]
On a 32-core machine, verifying v5.9 took 4h, v6.0 and v6.1 took ~18h, v6.2 took ~15h, and v6.3 took ~30.5h.
On the same machine, after 360h, v6.4 still wasn't fully verified.

After 360h, only `BPF_SUB` remained to be verified. I doubt it's specific to that instruction however because `BPF_ADD` for example also took many days to finish.

That run was without the update for v6.4 from https://github.com/bpfverif/ebpf-range-analysis-verification-cav23/pull/11, but I don't see how that would impact runtime that much. I've also since then stopped the 360h run and restarted it with the proper wrappers. So far the restart looks just as slow. 

<details>
<summary>Click here to see the full output of the ongoing v6.4 run.</summary>

```
# time python3 bpf_alu_jmp_synthesis.py --kernver 6.4 --encodings_path /root/paul/ebpf-verif-results-6.4

--------------------------------------------------------------
                EXPERIMENT SETUP
--------------------------------------------------------------

{'bpf_encodings_path': '/root/paul/ebpf-verif-results-6.4',
 'bug_dict': {},
 'insn_set': ['BPF_JLE_32',
              'BPF_JSLE_32',
              'BPF_JNE_32',
              'BPF_JGE_32',
              'BPF_JSGE_32',
              'BPF_JLE',
              'BPF_JNE',
              'BPF_JGE',
              'BPF_JSGE',
              'BPF_JSLE'],
 'json_offset': 3,
 'kernel_ver': '6.4',
 'num_synthesis_iter': 3,
 'title': 'verification and synthesis config file',
 'verification_set': ['BPF_AND',
                      'BPF_OR',
                      'BPF_LSH',
                      'BPF_RSH',
                      'BPF_JLT',
                      'BPF_JLE',
                      'BPF_JEQ',
                      'BPF_JNE',
                      'BPF_JGE',
                      'BPF_JGT',
                      'BPF_JSGE',
                      'BPF_JSGT',
                      'BPF_JSLT',
                      'BPF_JSLE',
                      'BPF_ADD',
                      'BPF_SUB',
                      'BPF_XOR',
                      'BPF_ARSH',
                      'BPF_OR_32',
                      'BPF_AND_32',
                      'BPF_LSH_32',
                      'BPF_RSH_32',
                      'BPF_ADD_32',
                      'BPF_SUB_32',
                      'BPF_XOR_32',
                      'BPF_ARSH_32',
                      'BPF_JLT_32',
                      'BPF_JLE_32',
                      'BPF_JSLT_32',
                      'BPF_JSLE_32',
                      'BPF_JEQ_32',
                      'BPF_JNE_32',
                      'BPF_JGE_32',
                      'BPF_JGT_32',
                      'BPF_JSGE_32',
                      'BPF_JSGT_32'],
 'write_dir_path': '/root/paul/ebpf-range-analysis-verification-cav23/bpf-verification/results'}

--------------------------------------------------------------
                2.1(a) Executing gen verification
--------------------------------------------------------------

2/36 Verifying BPF_LSH_32...
5/36 Verifying BPF_AND_32...
1/36 Verifying BPF_LSH...
3/36 Verifying BPF_XOR_32...
15/36 Verifying BPF_ADD_32...
16/36 Verifying BPF_SUB...
8/36 Verifying BPF_XOR...
27/36 Verifying BPF_RSH_32...
28/36 Verifying BPF_AND...
25/36 Verifying BPF_RSH...
17/36 Verifying BPF_SUB_32...
30/36 Verifying BPF_ARSH_32...
21/36 Verifying BPF_ARSH...
19/36 Verifying BPF_ADD...
0/36 Verifying BPF_JLE...
14/36 Verifying BPF_JSGE...
13/36 Verifying BPF_JSGT_32...
11/36 Verifying BPF_JSLE...
12/36 Verifying BPF_JSGE_32...
6/36 Verifying BPF_JLT_32...
7/36 Verifying BPF_JSLT...
4/36 Verifying BPF_JGT...
9/36 Verifying BPF_JSGT...
10/36 Verifying BPF_JNE_32...
26/36 Verifying BPF_JLT...
23/36 Verifying BPF_JLE_32...
22/36 Verifying BPF_JSLE_32...
29/36 Verifying BPF_JGE_32...
18/36 Verifying BPF_JGE...
20/36 Verifying BPF_JSLT_32...
31/36 Verifying BPF_JGT_32...
24/36 Verifying BPF_JEQ_32...
3/36 BPF_XOR_32 Done.
32/36 Verifying BPF_OR...
8/36 BPF_XOR Done.
33/36 Verifying BPF_JEQ...
5/36 BPF_AND_32 Done.
34/36 Verifying BPF_JNE...
28/36 BPF_AND Done.
35/36 Verifying BPF_OR_32...
27/36 BPF_RSH_32 Done.
35/36 BPF_OR_32 Done.
32/36 BPF_OR Done.
2/36 BPF_LSH_32 Done.
30/36 BPF_ARSH_32 Done.
25/36 BPF_RSH Done.
21/36 BPF_ARSH Done.
1/36 BPF_LSH Done.
15/36 BPF_ADD_32 Done.
10/36 BPF_JNE_32 Done.
24/36 BPF_JEQ_32 Done.
17/36 BPF_SUB_32 Done.
20/36 BPF_JSLT_32 Done.
31/36 BPF_JGT_32 Done.
6/36 BPF_JLT_32 Done.
22/36 BPF_JSLE_32 Done.
12/36 BPF_JSGE_32 Done.
23/36 BPF_JLE_32 Done.
13/36 BPF_JSGT_32 Done.
29/36 BPF_JGE_32 Done.
34/36 BPF_JNE Done.
33/36 BPF_JEQ Done.
4/36 BPF_JGT Done.
9/36 BPF_JSGT Done.
7/36 BPF_JSLT Done.
18/36 BPF_JGE Done.
26/36 BPF_JLT Done.
11/36 BPF_JSLE Done.
0/36 BPF_JLE Done.
14/36 BPF_JSGE Done.
19/36 BPF_ADD Done.
```
</details>

I also have a v6.5 run ongoing (with https://github.com/bpfverif/ebpf-range-analysis-verification-cav23/pull/7 and https://github.com/bpfverif/ebpf-range-analysis-verification-cav23/pull/11 applied) and it looks slow as well.

**Comment by pchaigno** [comment]
I have a bit more information from the three ongoing runs on v6.4, v6.5, and v6.6. The issue is always about `BPF_SUB` and `BPF_ADD`; all other instructions are verified much faster (few days max.). Interestingly, `BPF_SUB_32` and `BPF_ADD_32` were verified pretty quickly (hours).

I'll probably start a bisect next. I'll focus on suspicious verifier commits, but even then, given the type of issue, it's going to take a while. Maybe I can speed things up by verifying `BPF_ADD` on 32 commits in parallel...

**Comment by pchaigno** [comment]
Confirmed fixed at https://github.com/pchaigno/agni/actions/runs/8724061577?pr=3. BPF_ADD took 6h to verify with v6.4 on GitHub workflow.

**Comment by harishankarv** [comment]
For the sound kernels, we can perform modular verification. This support was added in 5c3fc4185d7632cbd585baf0a55c1c07f3180c66. 

1. Generate "modular" encodings, that is, encodings without `reg_bounds_sync()`, so that the size of the encodings is small. To do this `generate_encodings.py` supports a `--modular` flag. 
2.1 Perform verifcation using `bpf_alu_jmp_synthesis.py` as usual. For the sound kernels (>= 5.13) this should finish in around a minute or so on my M2 Mac. All the operators should be found to be sound after `sro` verification.
2.2 Perform verification of `reg_bounds_sync` separetely, by providing the switch `--ver_set BPF_SYNC`.  This takes around 20 minutes on my M2 Mac. 
We compose the soundness of 2.1 (op) and 2.2 (reg_bounds_sync) to claim that op + reg_bounds_sync is sound.

**Comment by harishankarv** [comment]
Of course, we cannot know if a kernel is sound beforehand. So the idea should be to perform modular verification. If It is fails or is unsound, we should proceed to perform full verification.

**Comment by pchaigno** [comment]
I totally missed that flag :facepalm: 

One point I'm not sure I understand: do I have to perform 2.1 and 2.2 manually by generating two sets of encodings (with and without `reg_bounds_sync`) or is that all automated?

**Comment by harishankarv** [comment]
You don't have to generate two sets of encodings. The effect of the `--modular` is exactly that it generates encodings without `reg_bounds_sync`. 

In `bpf_alu_jmp_synthesis.py`: Verification can proceed as usual because it doesn't matter to the verification *what* encodings were used . So first, just run `bpf_alu_jmp_synthesis.py` in the usual way (this is step 2.1). Now, since `reg_bounds_sync()` was removed from the encodings previously, we need to verify it separately. When we specify `--ver_set BPF_SYNC`, the script will perform verification for only `reg_bounds_sync()` (this is step 2.2).

**Comment by pchaigno** [comment]
Should we consider this addressed with the modular verification mode or is there hope to improve things even further?

**Comment by harishankarv** [comment]
@pchaigno can we close this issue in the light of the new modular verification approach added in https://github.com/bpfverif/agni/commit/5c3fc4185d7632cbd585baf0a55c1c07f3180c66?  

Only thing to note: this might mean if we include  instructions that require a lot of time for verification (e.g. BPF_SUB) to github workflows, we will need to use the modular verification approach, as described in the previous [comment](https://github.com/bpfverif/agni/issues/13#issuecomment-2065663144).

**Comment by harishankarv** [comment]
Oh I suppose we were typing our comments simultaneously 😄 . I think we can close this.

**Comment by pchaigno** [comment]
If that's not good timing :sweat_smile:
