### ISSUE TITLE
Modular encodings of jump instructions on v6.6: `GEPMapValuePhiArg is neither a selectInst nor a PHINode`

### ISSUE THREAD

**Issue by pchaigno** [bpfverif/agni#39]
I'm failing to generate modular encodings for kernel v6.6 for 64-bit jump instructions, due to the following error:
```
[handleStoreToPhiPtr] phiPtrInstBB: if.end184.sink.split
[handleStoreToPhiPtr] phiArgValI:   %u32_min_value13.i = getelementptr inbounds %struct.bpf_reg_state, %struct.bpf_reg_state* %other_branch_dst_reg, i64 0, i32 10
[handleStoreToPhiPtr] phiArgBBI: land.lhs.true7.i211.i
[handleStoreToPhiPtr] GEPMapValuePhiArg: %struct.bpf_reg_state* %other_branch_dst_reg
terminate called after throwing an instance of 'std::runtime_error'
  what():  [handleStoreToPhiPtr]: GEPMapValuePhiArg is neither a selectInst nor a PHINode. This is not supported.
```
The issue can also be seen in a CI run of an ongoing PR: https://github.com/bpfverif/agni/actions/runs/10065907452/job/27826066547?pr=37.

**Comment by pchaigno** [comment]
Same issue on v6.5, v6.4, and v6.7 (but those are not LTS).

**Comment by harishankarv** [comment]
Strange that non-modular (monolith) encodings work fine, but modular don't

**Comment by harishankarv** [comment]
Update: Using llvm-12 works fine -- was able modular encodings are generated successfully. Note that to use llvm-12 we need to revert 369287c26385aae3d63fa5c0f8e0a99a6e3ed0e4 otherwise we get the [LLVM out of memory error.](https://github.com/bpfverif/agni/wiki/Common-errors-and-how-to-handle-them).
